<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [

            // Africa
            ['name' => 'Algeria', 'iso_code' => 'DZA', 'continent' => 'Africa'],
            ['name' => 'Angola', 'iso_code' => 'AGO', 'continent' => 'Africa'],
            ['name' => 'Benin', 'iso_code' => 'BEN', 'continent' => 'Africa'],
            ['name' => 'Botswana', 'iso_code' => 'BWA', 'continent' => 'Africa'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BFA', 'continent' => 'Africa'],
            ['name' => 'Burundi', 'iso_code' => 'BDI', 'continent' => 'Africa'],
            ['name' => 'Cabo Verde', 'iso_code' => 'CPV', 'continent' => 'Africa'],
            ['name' => 'Cameroon', 'iso_code' => 'CMR', 'continent' => 'Africa'],
            ['name' => 'Central African Republic', 'iso_code' => 'CAF', 'continent' => 'Africa'],
            ['name' => 'Chad', 'iso_code' => 'TCD', 'continent' => 'Africa'],
            ['name' => 'Comoros', 'iso_code' => 'COM', 'continent' => 'Africa'],
            ['name' => 'Congo (Republic)', 'iso_code' => 'COG', 'continent' => 'Africa'],
            ['name' => 'Congo (DRC)', 'iso_code' => 'COD', 'continent' => 'Africa'],
            ['name' => "Côte d'Ivoire", 'iso_code' => 'CIV', 'continent' => 'Africa'],
            ['name' => 'Djibouti', 'iso_code' => 'DJI', 'continent' => 'Africa'],
            ['name' => 'Egypt', 'iso_code' => 'EGY', 'continent' => 'Africa'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GNQ', 'continent' => 'Africa'],
            ['name' => 'Eritrea', 'iso_code' => 'ERI', 'continent' => 'Africa'],
            ['name' => 'Eswatini', 'iso_code' => 'SWZ', 'continent' => 'Africa'],
            ['name' => 'Ethiopia', 'iso_code' => 'ETH', 'continent' => 'Africa'],
            ['name' => 'Gabon', 'iso_code' => 'GAB', 'continent' => 'Africa'],
            ['name' => 'Gambia', 'iso_code' => 'GMB', 'continent' => 'Africa'],
            ['name' => 'Ghana', 'iso_code' => 'GHA', 'continent' => 'Africa'],
            ['name' => 'Guinea', 'iso_code' => 'GIN', 'continent' => 'Africa'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GNB', 'continent' => 'Africa'],
            ['name' => 'Kenya', 'iso_code' => 'KEN', 'continent' => 'Africa'],
            ['name' => 'Lesotho', 'iso_code' => 'LSO', 'continent' => 'Africa'],
            ['name' => 'Liberia', 'iso_code' => 'LBR', 'continent' => 'Africa'],
            ['name' => 'Libya', 'iso_code' => 'LBY', 'continent' => 'Africa'],
            ['name' => 'Madagascar', 'iso_code' => 'MDG', 'continent' => 'Africa'],
            ['name' => 'Malawi', 'iso_code' => 'MWI', 'continent' => 'Africa'],
            ['name' => 'Mali', 'iso_code' => 'MLI', 'continent' => 'Africa'],
            ['name' => 'Mauritania', 'iso_code' => 'MRT', 'continent' => 'Africa'],
            ['name' => 'Mauritius', 'iso_code' => 'MUS', 'continent' => 'Africa'],
            ['name' => 'Morocco', 'iso_code' => 'MAR', 'continent' => 'Africa'],
            ['name' => 'Mozambique', 'iso_code' => 'MOZ', 'continent' => 'Africa'],
            ['name' => 'Namibia', 'iso_code' => 'NAM', 'continent' => 'Africa'],
            ['name' => 'Niger', 'iso_code' => 'NER', 'continent' => 'Africa'],
            ['name' => 'Nigeria', 'iso_code' => 'NGA', 'continent' => 'Africa'],
            ['name' => 'Rwanda', 'iso_code' => 'RWA', 'continent' => 'Africa'],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'STP', 'continent' => 'Africa'],
            ['name' => 'Senegal', 'iso_code' => 'SEN', 'continent' => 'Africa'],
            ['name' => 'Seychelles', 'iso_code' => 'SYC', 'continent' => 'Africa'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SLE', 'continent' => 'Africa'],
            ['name' => 'Somalia', 'iso_code' => 'SOM', 'continent' => 'Africa'],
            ['name' => 'South Africa', 'iso_code' => 'ZAF', 'continent' => 'Africa'],
            ['name' => 'South Sudan', 'iso_code' => 'SSD', 'continent' => 'Africa'],
            ['name' => 'Sudan', 'iso_code' => 'SDN', 'continent' => 'Africa'],
            ['name' => 'Tanzania', 'iso_code' => 'TZA', 'continent' => 'Africa'],
            ['name' => 'Togo', 'iso_code' => 'TGO', 'continent' => 'Africa'],
            ['name' => 'Tunisia', 'iso_code' => 'TUN', 'continent' => 'Africa'],
            ['name' => 'Uganda', 'iso_code' => 'UGA', 'continent' => 'Africa'],
            ['name' => 'Zambia', 'iso_code' => 'ZMB', 'continent' => 'Africa'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZWE', 'continent' => 'Africa'],

            // Europe
            ['name' => 'Albania', 'iso_code' => 'ALB', 'continent' => 'Europe'],
            ['name' => 'Andorra', 'iso_code' => 'AND', 'continent' => 'Europe'],
            ['name' => 'Austria', 'iso_code' => 'AUT', 'continent' => 'Europe'],
            ['name' => 'Belarus', 'iso_code' => 'BLR', 'continent' => 'Europe'],
            ['name' => 'Belgium', 'iso_code' => 'BEL', 'continent' => 'Europe'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BIH', 'continent' => 'Europe'],
            ['name' => 'Bulgaria', 'iso_code' => 'BGR', 'continent' => 'Europe'],
            ['name' => 'Croatia', 'iso_code' => 'HRV', 'continent' => 'Europe'],
            ['name' => 'Cyprus', 'iso_code' => 'CYP', 'continent' => 'Europe'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZE', 'continent' => 'Europe'],
            ['name' => 'Denmark', 'iso_code' => 'DNK', 'continent' => 'Europe'],
            ['name' => 'Estonia', 'iso_code' => 'EST', 'continent' => 'Europe'],
            ['name' => 'Finland', 'iso_code' => 'FIN', 'continent' => 'Europe'],
            ['name' => 'France', 'iso_code' => 'FRA', 'continent' => 'Europe'],
            ['name' => 'Germany', 'iso_code' => 'DEU', 'continent' => 'Europe'],
            ['name' => 'Greece', 'iso_code' => 'GRC', 'continent' => 'Europe'],
            ['name' => 'Hungary', 'iso_code' => 'HUN', 'continent' => 'Europe'],
            ['name' => 'Iceland', 'iso_code' => 'ISL', 'continent' => 'Europe'],
            ['name' => 'Ireland', 'iso_code' => 'IRL', 'continent' => 'Europe'],
            ['name' => 'Italy', 'iso_code' => 'ITA', 'continent' => 'Europe'],
            ['name' => 'Latvia', 'iso_code' => 'LVA', 'continent' => 'Europe'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LIE', 'continent' => 'Europe'],
            ['name' => 'Lithuania', 'iso_code' => 'LTU', 'continent' => 'Europe'],
            ['name' => 'Luxembourg', 'iso_code' => 'LUX', 'continent' => 'Europe'],
            ['name' => 'Malta', 'iso_code' => 'MLT', 'continent' => 'Europe'],
            ['name' => 'Moldova', 'iso_code' => 'MDA', 'continent' => 'Europe'],
            ['name' => 'Monaco', 'iso_code' => 'MCO', 'continent' => 'Europe'],
            ['name' => 'Montenegro', 'iso_code' => 'MNE', 'continent' => 'Europe'],
            ['name' => 'Netherlands', 'iso_code' => 'NLD', 'continent' => 'Europe'],
            ['name' => 'North Macedonia', 'iso_code' => 'MKD', 'continent' => 'Europe'],
            ['name' => 'Norway', 'iso_code' => 'NOR', 'continent' => 'Europe'],
            ['name' => 'Poland', 'iso_code' => 'POL', 'continent' => 'Europe'],
            ['name' => 'Portugal', 'iso_code' => 'PRT', 'continent' => 'Europe'],
            ['name' => 'Romania', 'iso_code' => 'ROU', 'continent' => 'Europe'],
            ['name' => 'Russia', 'iso_code' => 'RUS', 'continent' => 'Europe'],
            ['name' => 'San Marino', 'iso_code' => 'SMR', 'continent' => 'Europe'],
            ['name' => 'Serbia', 'iso_code' => 'SRB', 'continent' => 'Europe'],
            ['name' => 'Slovakia', 'iso_code' => 'SVK', 'continent' => 'Europe'],
            ['name' => 'Slovenia', 'iso_code' => 'SVN', 'continent' => 'Europe'],
            ['name' => 'Spain', 'iso_code' => 'ESP', 'continent' => 'Europe'],
            ['name' => 'Sweden', 'iso_code' => 'SWE', 'continent' => 'Europe'],
            ['name' => 'Switzerland', 'iso_code' => 'CHE', 'continent' => 'Europe'],
            ['name' => 'Ukraine', 'iso_code' => 'UKR', 'continent' => 'Europe'],
            ['name' => 'United Kingdom', 'iso_code' => 'GBR', 'continent' => 'Europe'],
            ['name' => 'Vatican City', 'iso_code' => 'VAT', 'continent' => 'Europe'],

            // Asia
            ['name' => 'Afghanistan', 'iso_code' => 'AFG', 'continent' => 'Asia'],
            ['name' => 'Armenia', 'iso_code' => 'ARM', 'continent' => 'Asia'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZE', 'continent' => 'Asia'],
            ['name' => 'Bahrain', 'iso_code' => 'BHR', 'continent' => 'Asia'],
            ['name' => 'Bangladesh', 'iso_code' => 'BGD', 'continent' => 'Asia'],
            ['name' => 'Bhutan', 'iso_code' => 'BTN', 'continent' => 'Asia'],
            ['name' => 'Brunei', 'iso_code' => 'BRN', 'continent' => 'Asia'],
            ['name' => 'Cambodia', 'iso_code' => 'KHM', 'continent' => 'Asia'],
            ['name' => 'China', 'iso_code' => 'CHN', 'continent' => 'Asia'],
            ['name' => 'Georgia', 'iso_code' => 'GEO', 'continent' => 'Asia'],
            ['name' => 'India', 'iso_code' => 'IND', 'continent' => 'Asia'],
            ['name' => 'Indonesia', 'iso_code' => 'IDN', 'continent' => 'Asia'],
            ['name' => 'Iran', 'iso_code' => 'IRN', 'continent' => 'Asia'],
            ['name' => 'Iraq', 'iso_code' => 'IRQ', 'continent' => 'Asia'],
            ['name' => 'Israel', 'iso_code' => 'ISR', 'continent' => 'Asia'],
            ['name' => 'Japan', 'iso_code' => 'JPN', 'continent' => 'Asia'],
            ['name' => 'Jordan', 'iso_code' => 'JOR', 'continent' => 'Asia'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KAZ', 'continent' => 'Asia'],
            ['name' => 'Kuwait', 'iso_code' => 'KWT', 'continent' => 'Asia'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KGZ', 'continent' => 'Asia'],
            ['name' => 'Laos', 'iso_code' => 'LAO', 'continent' => 'Asia'],
            ['name' => 'Lebanon', 'iso_code' => 'LBN', 'continent' => 'Asia'],
            ['name' => 'Malaysia', 'iso_code' => 'MYS', 'continent' => 'Asia'],
            ['name' => 'Maldives', 'iso_code' => 'MDV', 'continent' => 'Asia'],
            ['name' => 'Mongolia', 'iso_code' => 'MNG', 'continent' => 'Asia'],
            ['name' => 'Myanmar', 'iso_code' => 'MMR', 'continent' => 'Asia'],
            ['name' => 'Nepal', 'iso_code' => 'NPL', 'continent' => 'Asia'],
            ['name' => 'North Korea', 'iso_code' => 'PRK', 'continent' => 'Asia'],
            ['name' => 'Oman', 'iso_code' => 'OMN', 'continent' => 'Asia'],
            ['name' => 'Pakistan', 'iso_code' => 'PAK', 'continent' => 'Asia'],
            ['name' => 'Palestine', 'iso_code' => 'PSE', 'continent' => 'Asia'],
            ['name' => 'Philippines', 'iso_code' => 'PHL', 'continent' => 'Asia'],
            ['name' => 'Qatar', 'iso_code' => 'QAT', 'continent' => 'Asia'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SAU', 'continent' => 'Asia'],
            ['name' => 'Singapore', 'iso_code' => 'SGP', 'continent' => 'Asia'],
            ['name' => 'South Korea', 'iso_code' => 'KOR', 'continent' => 'Asia'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LKA', 'continent' => 'Asia'],
            ['name' => 'Syria', 'iso_code' => 'SYR', 'continent' => 'Asia'],
            ['name' => 'Taiwan', 'iso_code' => 'TWN', 'continent' => 'Asia'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJK', 'continent' => 'Asia'],
            ['name' => 'Thailand', 'iso_code' => 'THA', 'continent' => 'Asia'],
            ['name' => 'Timor-Leste', 'iso_code' => 'TLS', 'continent' => 'Asia'],
            ['name' => 'Turkey', 'iso_code' => 'TUR', 'continent' => 'Asia'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TKM', 'continent' => 'Asia'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'ARE', 'continent' => 'Asia'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZB', 'continent' => 'Asia'],
            ['name' => 'Vietnam', 'iso_code' => 'VNM', 'continent' => 'Asia'],
            ['name' => 'Yemen', 'iso_code' => 'YEM', 'continent' => 'Asia'],

            // North America
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'ATG', 'continent' => 'North America'],
            ['name' => 'Bahamas', 'iso_code' => 'BHS', 'continent' => 'North America'],
            ['name' => 'Barbados', 'iso_code' => 'BRB', 'continent' => 'North America'],
            ['name' => 'Belize', 'iso_code' => 'BLZ', 'continent' => 'North America'],
            ['name' => 'Canada', 'iso_code' => 'CAN', 'continent' => 'North America'],
            ['name' => 'Costa Rica', 'iso_code' => 'CRI', 'continent' => 'North America'],
            ['name' => 'Cuba', 'iso_code' => 'CUB', 'continent' => 'North America'],
            ['name' => 'Dominica', 'iso_code' => 'DMA', 'continent' => 'North America'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DOM', 'continent' => 'North America'],
            ['name' => 'El Salvador', 'iso_code' => 'SLV', 'continent' => 'North America'],
            ['name' => 'Grenada', 'iso_code' => 'GRD', 'continent' => 'North America'],
            ['name' => 'Guatemala', 'iso_code' => 'GTM', 'continent' => 'North America'],
            ['name' => 'Haiti', 'iso_code' => 'HTI', 'continent' => 'North America'],
            ['name' => 'Honduras', 'iso_code' => 'HND', 'continent' => 'North America'],
            ['name' => 'Jamaica', 'iso_code' => 'JAM', 'continent' => 'North America'],
            ['name' => 'Mexico', 'iso_code' => 'MEX', 'continent' => 'North America'],
            ['name' => 'Nicaragua', 'iso_code' => 'NIC', 'continent' => 'North America'],
            ['name' => 'Panama', 'iso_code' => 'PAN', 'continent' => 'North America'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KNA', 'continent' => 'North America'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LCA', 'continent' => 'North America'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VCT', 'continent' => 'North America'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TTO', 'continent' => 'North America'],
            ['name' => 'United States', 'iso_code' => 'USA', 'continent' => 'North America'],

            // South America
            ['name' => 'Argentina', 'iso_code' => 'ARG', 'continent' => 'South America'],
            ['name' => 'Bolivia', 'iso_code' => 'BOL', 'continent' => 'South America'],
            ['name' => 'Brazil', 'iso_code' => 'BRA', 'continent' => 'South America'],
            ['name' => 'Chile', 'iso_code' => 'CHL', 'continent' => 'South America'],
            ['name' => 'Colombia', 'iso_code' => 'COL', 'continent' => 'South America'],
            ['name' => 'Ecuador', 'iso_code' => 'ECU', 'continent' => 'South America'],
            ['name' => 'Guyana', 'iso_code' => 'GUY', 'continent' => 'South America'],
            ['name' => 'Paraguay', 'iso_code' => 'PRY', 'continent' => 'South America'],
            ['name' => 'Peru', 'iso_code' => 'PER', 'continent' => 'South America'],
            ['name' => 'Suriname', 'iso_code' => 'SUR', 'continent' => 'South America'],
            ['name' => 'Uruguay', 'iso_code' => 'URY', 'continent' => 'South America'],
            ['name' => 'Venezuela', 'iso_code' => 'VEN', 'continent' => 'South America'],

            // Oceania
            ['name' => 'Australia', 'iso_code' => 'AUS', 'continent' => 'Oceania'],
            ['name' => 'Fiji', 'iso_code' => 'FJI', 'continent' => 'Oceania'],
            ['name' => 'Kiribati', 'iso_code' => 'KIR', 'continent' => 'Oceania'],
            ['name' => 'Marshall Islands', 'iso_code' => 'MHL', 'continent' => 'Oceania'],
            ['name' => 'Micronesia', 'iso_code' => 'FSM', 'continent' => 'Oceania'],
            ['name' => 'Nauru', 'iso_code' => 'NRU', 'continent' => 'Oceania'],
            ['name' => 'New Zealand', 'iso_code' => 'NZL', 'continent' => 'Oceania'],
            ['name' => 'Palau', 'iso_code' => 'PLW', 'continent' => 'Oceania'],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PNG', 'continent' => 'Oceania'],
            ['name' => 'Samoa', 'iso_code' => 'WSM', 'continent' => 'Oceania'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SLB', 'continent' => 'Oceania'],
            ['name' => 'Tonga', 'iso_code' => 'TON', 'continent' => 'Oceania'],
            ['name' => 'Tuvalu', 'iso_code' => 'TUV', 'continent' => 'Oceania'],
            ['name' => 'Vanuatu', 'iso_code' => 'VUT', 'continent' => 'Oceania'],
        ];

        foreach ($countries as $country) {
            \App\Models\Country::updateOrCreate(
                ['iso_code' => $country['iso_code']],
                $country
            );
        }
    }
}
